//
// Created by arthur on 12/08/2023.
//

#ifdef CCT_ENABLE_ENET

#ifndef CONCERTO_CORE_NETWORK_ENET_ADDRESS_HPP
#define CONCERTO_CORE_NETWORK_ENET_ADDRESS_HPP

namespace cct::net
{

}

#endif // CONCERTO_CORE_NETWORK_ENET_ADDRESS_HPP

#endif // CCT_ENABLE_ENET