//
// JsonPlugin.c - Generates .Accept.gen.cpp files with static Accept(FieldVisitor&)
// overrides for every reflected class, dispatching each member to the right
// FieldVisitor::Visit overload via C++ overload resolution.
//
// This eliminates the runtime dynamic_cast and class-name string comparisons
// in Object::Accept()'s default fallback implementation.
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "Concerto/PackageGenerator/Plugin/PluginApi.h"

typedef struct JsonPluginData
{
	int currentClassSkipped; // 1 while generating a class that should be skipped
	int inTemplateSpecialization; // 1 inside a template specialization Accept body
} JsonPluginData;

// --- Metadata ---

static void GetInfo(CrpPluginInfo* outInfo)
{
	outInfo->name = "JsonPlugin";
	outInfo->version = "1.0.0";
	outInfo->author = "Concerto";
	outInfo->description = "Generates Accept(FieldVisitor&) overrides for reflected classes";
	outInfo->outputFileExtension = ".Accept.gen.cpp";
}

static int32_t GetPriority(void)
{
	// After HeaderPlugin (100) and CppPlugin (0 or similar).
	return 40;
}

static int32_t OnLoad(void** outPrivateData)
{
	JsonPluginData* data = (JsonPluginData*)calloc(1, sizeof(JsonPluginData));
	if (!data)
		return 0;
	if (outPrivateData)
		*outPrivateData = data;
	return 1;
}

static void OnUnload(void* privateData)
{
	free(privateData);
}

// --- Helpers ---

static const char* UnqualifiedName(const char* fullName)
{
	if (!fullName)
		return "";
	const char* p = strrchr(fullName, ':');
	return p ? p + 1 : fullName;
}

// Returns 1 if the base class is cct::refl::Object (or just "Object"),
// meaning we should NOT chain the base Accept() call — the default
// Object::Accept() is the runtime-reflection fallback and must not be
// invoked from a generated override or it would traverse all fields again.
static int IsObjectBase(const char* baseName)
{
	if (!baseName)
		return 1;
	return strcmp(UnqualifiedName(baseName), "Object") == 0;
}

// --- Hooks ---

static void BeforePackageGeneration(const CrpPackage* package, CrpGenerationContext* ctx)
{
	(void)package;
	crpGenerationContextWrite(ctx, "// AUTO-GENERATED by JsonPlugin. DO NOT EDIT.");
	crpGenerationContextWrite(ctx, "// Generates cct::refl::FieldVisitor Accept() overrides for reflected classes.");
	crpGenerationContextNewLine(ctx);

	crpGenerationContextWrite(ctx, "#include \"Concerto/Reflection/FieldVisitor/FieldVisitor.hpp\"");
	crpGenerationContextNewLine(ctx);

	size_t headerCount = crpGenerationContextGetHeaderCount(ctx);
	for (size_t i = 0; i < headerCount; ++i)
	{
		const char* header = crpGenerationContextGetHeader(ctx, i);
		crpGenerationContextWrite(ctx, "#include \"%s\"", header);
	}
	crpGenerationContextNewLine(ctx);
}

static void BeforeClassGeneration(const CrpClass* cls, CrpGenerationContext* ctx)
{
	const char* className = crpClassGetName(cls);
	const char* baseName = crpClassGetBase(cls);
	JsonPluginData* data = (JsonPluginData*)crpGenerationContextGetPrivateData(ctx);

	// Skip the root Object class — it has a hand-written runtime-reflection fallback
	// in Object.cpp and has no serializable members of its own.
	if (baseName == NULL)
	{
		if (data)
			data->currentClassSkipped = 1;
		return;
	}
	if (data)
		data->currentClassSkipped = 0;

	// Use the actual C++ namespace path, not the annotation kind returned by crpClassGetScope.
	const char* scope = crpGenerationContextGetNamespacePath(ctx);

	if (scope != NULL && scope[0] != '\0')
	{
		crpGenerationContextWrite(ctx, "void %s::%s::Accept(cct::refl::FieldVisitor& v)",
								  scope, className);
	}
	else
	{
		crpGenerationContextWrite(ctx, "void %s::Accept(cct::refl::FieldVisitor& v)", className);
	}
	crpGenerationContextEnterScope(ctx);

	// Chain to the base class's generated Accept() — but not to Object::Accept()
	// (which is the runtime-reflection fallback and would double-visit all fields).
	if (!IsObjectBase(baseName))
	{
		crpGenerationContextWrite(ctx, "%s::Accept(v);", baseName);
	}
}

static void OnMemberGeneration(const CrpClassMember* member, CrpGenerationContext* ctx)
{
	JsonPluginData* data = (JsonPluginData*)crpGenerationContextGetPrivateData(ctx);
	if (data && data->currentClassSkipped)
	{
		return;
	}

	const char* type = crpClassMemberGetType(member);
	if (!type)
	{
		return;
	}

	// Pointer types are never serializable.
	if (strchr(type, '*') != NULL)
	{
		return;
	}

	if (crpClassMemberIsNative(member))
	{
		// Inside a template specialization the member types are the template parameter
		// names (e.g. "K", "V"), not concrete types — accept all non-pointer natives.
		int inSpec = data && data->inTemplateSpecialization;
		if (!inSpec)
		{
			if (!(strcmp(type, "bool") == 0 ||
				  strcmp(type, "int") == 0 ||
				  strcmp(type, "float") == 0 ||
				  strcmp(type, "std::string") == 0 ||
				  strcmp(type, "string") == 0))
			{
				return;
			}
		}
	}

	const char* fieldName = crpClassMemberGetName(member);
	const char* jsonKey = (strncmp(fieldName, "m_", 2) == 0) ? fieldName + 2 : fieldName;

	crpGenerationContextWrite(ctx, "v.Visit(\"%s\", %s);", jsonKey, fieldName);
}

static void AfterClassGeneration(const CrpClass* cls, CrpGenerationContext* ctx)
{
	(void)cls;
	JsonPluginData* data = (JsonPluginData*)crpGenerationContextGetPrivateData(ctx);
	if (data && data->currentClassSkipped)
	{
		data->currentClassSkipped = 0;
		return;
	}
	crpGenerationContextLeaveScope(ctx, NULL);
	crpGenerationContextNewLine(ctx);
}

// Template class (unspecialized, e.g. TemplatedPair<K,V>) — skip entirely;
// each explicit specialization is handled by BeforeTemplateSpecializationGeneration.
static void BeforeTemplateClassGeneration(const CrpClass* cls, CrpGenerationContext* ctx)
{
	(void)cls;
	JsonPluginData* data = (JsonPluginData*)crpGenerationContextGetPrivateData(ctx);
	if (data)
		data->currentClassSkipped = 1;
}

static void AfterTemplateClassGeneration(const CrpClass* cls, CrpGenerationContext* ctx)
{
	(void)cls;
	JsonPluginData* data = (JsonPluginData*)crpGenerationContextGetPrivateData(ctx);
	if (data)
	{
		data->currentClassSkipped = 0;
	}
}

// Template specialization (e.g. TemplatedPair<int, float>).
// OnMemberGeneration is NOT called for specialization members by the generator,
// so we iterate members manually here using the class API.
static void BeforeTemplateSpecializationGeneration(const CrpClass* cls, const char* specialization, CrpGenerationContext* ctx)
{
	const char* className = crpClassGetName(cls);
	const char* baseName = crpClassGetBase(cls);
	const char* scope = crpGenerationContextGetNamespacePath(ctx);

	if (scope != NULL && scope[0] != '\0')
	{
		crpGenerationContextWrite(ctx, "void %s::%s<%s>::Accept(cct::refl::FieldVisitor& v)", scope, className, specialization);
	}
	else
	{
		crpGenerationContextWrite(ctx, "void %s<%s>::Accept(cct::refl::FieldVisitor& v)", className, specialization);
	}

	crpGenerationContextEnterScope(ctx);

	if (!IsObjectBase(baseName))
	{
		crpGenerationContextWrite(ctx, "%s<%s>::Accept(v);", className, specialization);
	}

	// Emit v.Visit() for each member. Template parameter types (e.g. "K", "V") are native
	// but not in the normal supported list — accept all non-pointer native types here.
	const size_t memberCount = crpClassGetMemberCount(cls);
	for (size_t i = 0; i < memberCount; ++i)
	{
		const CrpClassMember* member = crpClassGetMember(cls, i);
		const char* type = crpClassMemberGetType(member);
		if (!type)
		{
			continue;
		}
		if (strchr(type, '*') != NULL)
		{
			continue; // skip pointer types
		}
		const char* fieldName = crpClassMemberGetName(member);
		const char* jsonKey = (strncmp(fieldName, "m_", 2) == 0) ? fieldName + 2 : fieldName;
		crpGenerationContextWrite(ctx, "v.Visit(\"%s\", %s);", jsonKey, fieldName);
	}
}

static void AfterTemplateSpecializationGeneration(const CrpClass* cls, const char* specialization, CrpGenerationContext* ctx)
{
	(void)cls;
	(void)specialization;
	JsonPluginData* data = (JsonPluginData*)crpGenerationContextGetPrivateData(ctx);
	if (data)
	{
		data->inTemplateSpecialization = 0;
	}
	crpGenerationContextLeaveScope(ctx, NULL);
	crpGenerationContextNewLine(ctx);
}

// Generic class (CCT_GENERIC_CLASS) — same pattern as a regular class.
// Exception: Vector provides its own Accept that iterates m_elements polymorphically;
// generating a conflicting empty override would break serialization.
static void BeforeGenericClassGeneration(const CrpClass* cls, CrpGenerationContext* ctx)
{
	const char* className = crpClassGetName(cls);
	JsonPluginData* data = (JsonPluginData*)crpGenerationContextGetPrivateData(ctx);
	if (strcmp(className, "Vector") == 0)
	{
		if (data)
		{
			data->currentClassSkipped = 1;
		}
		return;
	}
	BeforeClassGeneration(cls, ctx);
}

static void AfterGenericClassGeneration(const CrpClass* cls, CrpGenerationContext* ctx)
{
	AfterClassGeneration(cls, ctx);
}

// --- Function table ---

static const CrpPluginFunctionTable g_pluginTable = {
	.apiVersion = CRP_PLUGIN_API_VERSION,
	.GetInfo = GetInfo,
	.GetPriority = GetPriority,
	.OnLoad = OnLoad,
	.OnUnload = OnUnload,
	.TransformPackage = NULL,

	.BeforePackageGeneration = BeforePackageGeneration,
	.OnPackageGeneration = NULL,
	.AfterPackageGeneration = NULL,

	.BeforeNamespaceGeneration = NULL,
	.OnNamespaceGeneration = NULL,
	.AfterNamespaceGeneration = NULL,

	.BeforeClassGeneration = BeforeClassGeneration,
	.OnClassGeneration = NULL,
	.AfterClassGeneration = AfterClassGeneration,

	.BeforeMemberGeneration = NULL,
	.OnMemberGeneration = OnMemberGeneration,
	.AfterMemberGeneration = NULL,

	.BeforeMethodGeneration = NULL,
	.OnMethodGeneration = NULL,
	.AfterMethodGeneration = NULL,

	.BeforeEnumGeneration = NULL,
	.OnEnumGeneration = NULL,
	.AfterEnumGeneration = NULL,

	.BeforeEnumElementGeneration = NULL,
	.OnEnumElementGeneration = NULL,
	.AfterEnumElementGeneration = NULL,

	.BeforeTemplateClassGeneration = BeforeTemplateClassGeneration,
	.OnTemplateClassGeneration = NULL,
	.AfterTemplateClassGeneration = AfterTemplateClassGeneration,

	.BeforeGenericClassGeneration = BeforeGenericClassGeneration,
	.OnGenericClassGeneration = NULL,
	.AfterGenericClassGeneration = AfterGenericClassGeneration,

	.BeforeTemplateSpecializationGeneration = BeforeTemplateSpecializationGeneration,
	.OnTemplateSpecializationGeneration = NULL,
	.AfterTemplateSpecializationGeneration = AfterTemplateSpecializationGeneration,

	.HandleAnnotation = NULL,
	.GenerateFile = NULL,
};

CRP_DECLARE_PLUGIN_ENTRY(g_pluginTable)
