//
// TsPlugin.c - Generates .gen.ts TypeScript type definitions mirroring
// the JSON wire format produced by cct::refl::Json::ToJson, so React
// frontends can stay in sync with C++ reflected classes automatically.
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "Concerto/PackageGenerator/Plugin/PluginApi.h"

typedef struct TsPluginData
{
	int reserved;
} TsPluginData;

// --- Plugin metadata ---

static void GetInfo(CrpPluginInfo* outInfo)
{
	outInfo->name = "TsPlugin";
	outInfo->version = "1.0.0";
	outInfo->author = "Concerto";
	outInfo->description = "Generates .gen.ts TypeScript type definitions for reflected classes";
	outInfo->outputFileExtension = ".gen.ts";
}

static int32_t GetPriority(void)
{
	// Between HeaderPlugin (100) and CppPlugin (0). Order has no functional impact for
	// .gen.ts since it doesn't depend on the .gen.hpp/.cpp output.
	return 50;
}

static int32_t OnLoad(void** outPrivateData)
{
	TsPluginData* data = (TsPluginData*)calloc(1, sizeof(TsPluginData));
	if (!data)
		return 0;
	if (outPrivateData)
		*outPrivateData = data;
	return 1;
}

static void OnUnload(void* privateData)
{
	free(privateData);
}

// --- Helpers ---

// Returns the part after the last "::" in a qualified C++ name.
static const char* UnqualifiedName(const char* fullName)
{
	if (!fullName)
		return "";
	const char* p = strrchr(fullName, ':');
	return p ? p + 1 : fullName;
}

// Maps a C++ member type string to a TypeScript type string. The mapping
// matches the wire format produced by cct::refl::Json::ToJson:
//   - primitive wrappers are flattened on m_value (Float32 -> number, etc.)
//   - Vector -> array (element type fixed at runtime, so unknown[])
//   - Enumeration -> EnumValue shape ({ $enum, value, options })
//   - other reflected Object subclasses -> reference by unqualified name
static const char* MapTypeToTs(const char* cppType, int isNative)
{
	if (!cppType)
		return "unknown";

	// Primitive wrappers (flattened by Json::ToJson onto m_value).
	if (strcmp(cppType, "cct::refl::Boolean") == 0)
		return "boolean";
	if (strcmp(cppType, "cct::refl::String") == 0)
		return "string";
	if (strncmp(cppType, "cct::refl::Int", 14) == 0)
		return "number";
	if (strncmp(cppType, "cct::refl::UInt", 15) == 0)
		return "number";
	if (strncmp(cppType, "cct::refl::Float", 16) == 0)
		return "number";

	// Special reflection containers.
	if (strcmp(cppType, "cct::refl::Vector") == 0)
		return "unknown[]";
	if (strcmp(cppType, "cct::refl::Enumeration") == 0)
		return "EnumValue";

	// Native C++ types.
	if (isNative)
	{
		if (strcmp(cppType, "bool") == 0)
			return "boolean";
		if (strcmp(cppType, "std::string") == 0)
			return "string";
		if (strcmp(cppType, "string") == 0)
			return "string";
		// Anything else native is a numeric primitive (int*, uint*, float, double, size_t, char, ...).
		return "number";
	}

	// Custom reflected Object — assume it's defined elsewhere in the same
	// generated file. The unqualified name is enough because we emit a flat file.
	return UnqualifiedName(cppType);
}

// Returns 1 if the base class should be ignored (i.e. cct::refl::Object) so we
// don't emit "extends Object" — the JSON wire format flattens to a plain object.
static int IsObjectBase(const char* baseName)
{
	if (!baseName)
		return 1;
	return strcmp(UnqualifiedName(baseName), "Object") == 0;
}

// --- Hooks ---

static void BeforePackageGeneration(const CrpPackage* package, CrpGenerationContext* ctx)
{
	(void)package;
	crpGenerationContextWrite(ctx, "// AUTO-GENERATED by TsPlugin. DO NOT EDIT.");
	crpGenerationContextWrite(ctx, "// Mirrors the wire format produced by cct::refl::Json::ToJson.");
	crpGenerationContextNewLine(ctx);

	crpGenerationContextWrite(ctx, "/** Wire shape of any cct::refl::Enumeration member, as serialized by Json::ToJson. */");
	crpGenerationContextWrite(ctx, "export type EnumValue<T extends string = string> = {");
	crpGenerationContextWrite(ctx, "\t$enum: string;");
	crpGenerationContextWrite(ctx, "\tvalue: T;");
	crpGenerationContextWrite(ctx, "\toptions: T[];");
	crpGenerationContextWrite(ctx, "};");
	crpGenerationContextNewLine(ctx);
}

static void BeforeEnumGeneration(const CrpEnum* enm, CrpGenerationContext* ctx)
{
	const char* enumName = crpEnumGetName(enm);
	crpGenerationContextWrite(ctx, "export enum %s", enumName);
	crpGenerationContextEnterScope(ctx);
}

static void OnEnumElementGeneration(const CrpEnumElement* elem, CrpGenerationContext* ctx)
{
	const char* name = crpEnumElementGetName(elem);
	// Use the element name as both key and string value so JSON serialization
	// (which uses the name) round-trips cleanly through this enum.
	crpGenerationContextWrite(ctx, "%s = '%s',", name, name);
}

static void AfterEnumGeneration(const CrpEnum* enm, CrpGenerationContext* ctx)
{
	(void)enm;
	crpGenerationContextLeaveScope(ctx, NULL);
	crpGenerationContextNewLine(ctx);
}

static void BeforeClassGeneration(const CrpClass* cls, CrpGenerationContext* ctx)
{
	const char* className = crpClassGetName(cls);
	const char* baseName = crpClassGetBase(cls);

	if (baseName != NULL && !IsObjectBase(baseName))
	{
		crpGenerationContextWrite(ctx, "export interface %s extends %s",
								  className, UnqualifiedName(baseName));
	}
	else
	{
		crpGenerationContextWrite(ctx, "export interface %s", className);
	}
	crpGenerationContextEnterScope(ctx);
}

static void OnMemberGeneration(const CrpClassMember* member, CrpGenerationContext* ctx)
{
	const char* memberName = crpClassMemberGetName(member);
	const char* memberType = crpClassMemberGetType(member);
	const int isNative = crpClassMemberIsNative(member);
	const char* tsType = MapTypeToTs(memberType, isNative);
	crpGenerationContextWrite(ctx, "%s: %s;", memberName, tsType);
}

static void AfterClassGeneration(const CrpClass* cls, CrpGenerationContext* ctx)
{
	(void)cls;
	crpGenerationContextLeaveScope(ctx, NULL);
	crpGenerationContextNewLine(ctx);
}

// --- Function table ---

static const CrpPluginFunctionTable g_pluginTable = {
	.apiVersion = CRP_PLUGIN_API_VERSION,
	.GetInfo = GetInfo,
	.GetPriority = GetPriority,
	.OnLoad = OnLoad,
	.OnUnload = OnUnload,
	.TransformPackage = NULL,

	.BeforePackageGeneration = BeforePackageGeneration,
	.OnPackageGeneration = NULL,
	.AfterPackageGeneration = NULL,

	// Skip namespace hooks — the JSON wire format is flat, so no TS namespace wrapping.
	.BeforeNamespaceGeneration = NULL,
	.OnNamespaceGeneration = NULL,
	.AfterNamespaceGeneration = NULL,

	.BeforeClassGeneration = BeforeClassGeneration,
	.OnClassGeneration = NULL,
	.AfterClassGeneration = AfterClassGeneration,

	.BeforeMemberGeneration = NULL,
	.OnMemberGeneration = OnMemberGeneration,
	.AfterMemberGeneration = NULL,

	.BeforeMethodGeneration = NULL,
	.OnMethodGeneration = NULL,
	.AfterMethodGeneration = NULL,

	.BeforeEnumGeneration = BeforeEnumGeneration,
	.OnEnumGeneration = NULL,
	.AfterEnumGeneration = AfterEnumGeneration,

	.BeforeEnumElementGeneration = NULL,
	.OnEnumElementGeneration = OnEnumElementGeneration,
	.AfterEnumElementGeneration = NULL,

	.BeforeTemplateClassGeneration = NULL,
	.OnTemplateClassGeneration = NULL,
	.AfterTemplateClassGeneration = NULL,

	.BeforeGenericClassGeneration = NULL,
	.OnGenericClassGeneration = NULL,
	.AfterGenericClassGeneration = NULL,

	.BeforeTemplateSpecializationGeneration = NULL,
	.OnTemplateSpecializationGeneration = NULL,
	.AfterTemplateSpecializationGeneration = NULL,

	.HandleAnnotation = NULL,
	.GenerateFile = NULL,
};

CRP_DECLARE_PLUGIN_ENTRY(g_pluginTable)
